### PR TITLE
fix(graph-cache-config): correct `IntrospectionData`

### PR DESCRIPTION
**Pull request by dargmuesli**
## Description

In `@urql/exchange-graphcache@v5.2.0` `IntrospectionData` is no longer exported, but can be accessed via `CacheExchangeOpts`'s schema property.

https://github.com/urql-graphql/urql/issues/3027#issuecomment-1463386912

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] This change requires a documentation update

## Screenshots/Sandbox (if appropriate/relevant):

n/a

## How Has This Been Tested?

Updated existing test & snapshot.

**Test Environment**:

CI

## Checklist:

- [x] I have followed the
      [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the
      style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

n/a

### CODE REVIEW

**Comment by dargmuesli** [comment]
I fixed the formatting :)

**Review by saihaj — APPROVED** [review]

**Comment by dargmuesli** [comment]
You're right, sorry. It's hard to see which of the many scripts one needs to run. I now went through all ci scripts and hope I got everything. Maybe there could be a "ci" script in the package.json which runs all necessary other scripts that need to run fine so one does not have to wait for each approval or go through the ci definition yml :smile:

**Comment by saihaj** [comment]
> You're right, sorry. It's hard to see which of the many scripts one needs to run. I now went through all ci scripts and hope I got everything. Maybe there could be a "ci" script in the package.json which runs all necessary other scripts that need to run fine so one does not have to wait for each approval or go through the ci definition yml 😄

feel free to send that PR and we can also update the docs for it!

**Comment by dargmuesli** [comment]
Updated to incorporate #314

**Comment by saihaj** [comment]
@dargmuesli i want to keep EOL node 12 independent so let’s revert that here.

**Comment by dargmuesli** [comment]
Will do once [the current GitHub incident](https://www.githubstatus.com/incidents/52z0j6phhnjs) is resolved :+1: Do you plan to merge this PR without all tests being green then?

**Comment by dargmuesli** [comment]
Done :heavy_check_mark:

**Review by saihaj — APPROVED** [review]

**Pull request merged**
