### PR TITLE
feat(flow): flow-operations tries to spread inexact objects #8000

### PR DESCRIPTION
**Pull request by Athelian**
🚨 **IMPORTANT: Please do not create a Pull Request without creating an issue first.**

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._

## Description
Flow-operations tries to spread exact/inexact objects into the same merged object which leads to flow errrors.
I have already been running with this change in a custom plugin for quite some time.

Related issue [#8000](https://github.com/dotansimha/graphql-code-generator-community/issues/198)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Screenshots/Sandbox (if appropriate/relevant):
[Flow Try demonstrating the issue](https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BM7c+A+Y2yU4IwRO4A6SFBIrGVDGL09ZIFkolXpUCWewUEAwhCQgRDH8wEH4hMnwROHlsNnw4KHwwSLAAC3wANyo4LFxscWQuN34NZmwsiRSAWglaY1cDEgBrbAlc2kbhXFx29y6evoHRHEoR2KgwUqpm1sCK-XchKCg6spIqfvTC0ww-WZBN7bBd-caIRn9obkbcjHSzzb2YbEaEHobKEiNMgSf7lSoGTZxJrMcJwMgjAC+-EgGiCAB0-CsAAQAEgACnAwJ0ADwAeVMCHSyCxpLQACs6hJeFiANLYWgkam0hnKAB8WIAvLjuQBZDCMODEtkc5lS9m8gAUnWp0oAlIL+TiAKKlcx+AAqKzJFPSzOlvN5AG4MRiWsYsQAlTQmQRXQVY4AAHxgxAA-NS0MRFlBPQibZj7U6vix5thDcYoM5sABJbaKZTu4BY-D4O2CJPUgDkUZdscLWLDEewjudMau8fz5i16Ykmc92dzK0T5iLJbr2HLofDeaxADEiAB3UnGGgPOyphReTMYrFYqzrvuuuNdpMLlu8Fdr9f4wkkzex5mHr1Yn0Qf1Yk60LGh3kYysY2z2G+T6cmSJwaASD3LxqXHCApxnf9AOAjMhWAHM827bBqTREBzyuVDmVvakpBkCth2xMCIL-OcSGbJc4MPdcrHQ7cEyTcjlAPKBV2ok8iWJWjLxYj121ve9H2fBFXygd95kA1sYB-SDSMYiRQOkkiALsOTMwQnceyxVDaMwm9iBw6RqzEmIQHyEwSGUoJ8gABisAAmOyAA4rGskAESAA)

## How Has This Been Tested?
[Pre-existing test demonstrates difference between `useFlowExactObjects=false/true`](https://github.com/Athelian/graphql-code-generator-community/blob/6367b288512a529af4df44e8ad0d49512616105a/packages/plugins/flow/operations/tests/flow-documents.spec.ts#L1168)

**Test Environment**:

- OS: Linux
- Flow: 0.181.2
- `@graphql-codegen/flow-operations` version: ^2.2.13

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments
Forked from legacy repo

### CODE REVIEW

**Comment by charlypoly** [comment]
Hi @Athelian,

Thank you for your contribution! ⚡ 

Could you check the following:
- fix ESLint issues (see PR files)
- Locally run `yarn generate:examples` and commit the diff (to fix the `dev-tests`)

Thank you!

**Comment by Athelian** [comment]
> Locally run yarn generate:examples and commit the diff (to fix the dev-tests)

Hi @charlypoly.

I think `yarn generate:examples` is failing on `main`, would you need extra hands on it?

And please lmk if you would prefer I rebase this PR instead of merge.

Thank you.

**Comment by saihaj** [comment]
Hey @Athelian can you please rebase this PR and hopefully that should make all tests pass then we can merge

**Comment by Athelian** [comment]
> Hey @Athelian can you please rebase this PR and hopefully that should make all tests pass then we can merge

Done!

**Comment by saihaj** [comment]
hey @Athelian can you please add a test for this change and also run `yarn changeset` and create a patch which helps with release. You can [learn here about changeset](https://github.com/dotansimha/graphql-code-generator-community/pull/15#issuecomment-1848353266)

**Comment by Athelian** [comment]
> hey @Athelian can you please add a test for this change and also run `yarn changeset` and create a patch which helps with release. You can [learn here about changeset](https://github.com/dotansimha/graphql-code-generator-community/pull/15#issuecomment-1848353266)

Hi @saihaj I added the changeset.

As for a new test, I am not sure if it is necessary: All pre-existing tests needed updating, and all differences between true/false can covered by [`Should respect flow option useFlowExactObjects=false`](https://github.com/Athelian/graphql-code-generator-community/blob/6367b288512a529af4df44e8ad0d49512616105a/packages/plugins/flow/operations/tests/flow-documents.spec.ts#L1168)

**Comment by saihaj** [comment]
CI is still failing @Athelian

**Comment by Athelian** [comment]
> CI is still failing @Athelian

Failing CI looks working to me now if replicate in local

**Review by saihaj — APPROVED** [review]
thank you for fixing!

**Comment by saihaj** [comment]
[@graphql-codegen/flow-operations@3.0.1](https://github.com/dotansimha/graphql-code-generator-community/releases/tag/release-1707842689733)

**Pull request merged**
