### PR TITLE
feat(typescript-urql-graphcache): mark @urql/exchange-graphcache v6 compatible

### PR DESCRIPTION
**Pull request by dargmuesli**
## Description

Resolves https://github.com/dotansimha/graphql-code-generator-community/issues/342

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] I have followed the
      [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the
      style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by frederikhors** [comment]
I remember that this change had already been made. I'm not understanding anything anymore.

**Comment by frederikhors** [comment]
Can you please merge this ASAP? Please.

**Comment by frederikhors** [comment]
Can you please merge this ASAP, @n1ru4l? Please...

**Comment by dargmuesli** [comment]
To me this contribution seems pretty cosmetic. Maybe give a reason why there is a need to rush? :smile:

**Comment by frederikhors** [comment]
> Maybe give a reason why there is a need to rush?

How wow - not cosmetic at all, this is the reason:

```
npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @graphql-codegen/typescript-urql-graphcache@2.4.5
npm ERR! Found: @urql/exchange-graphcache@6.1.0
npm ERR! node_modules/@urql/exchange-graphcache
npm ERR!   dev @urql/exchange-graphcache@"6.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @urql/exchange-graphcache@"^4.1.1 || ^5.0.0" from @graphql-codegen/typescript-urql-graphcache@2.4.5
npm ERR! node_modules/@graphql-codegen/typescript-urql-graphcache
npm ERR!   dev @graphql-codegen/typescript-urql-graphcache@"2.4.5" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @urql/exchange-graphcache@5.2.0
npm ERR! node_modules/@urql/exchange-graphcache
npm ERR!   peer @urql/exchange-graphcache@"^4.1.1 || ^5.0.0" from @graphql-codegen/typescript-urql-graphcache@2.4.5
npm ERR!   node_modules/@graphql-codegen/typescript-urql-graphcache
npm ERR!     dev @graphql-codegen/typescript-urql-graphcache@"2.4.5" from the root project
```

**Comment by dargmuesli** [comment]
Looking at https://github.com/npm/cli/issues/3666 maybe consider using pnpm or yarn instead or configure npm so that peer dependencies are not strict :bulb:

**Comment by frederikhors** [comment]
> Looking at [npm/cli#3666](https://github.com/npm/cli/issues/3666) maybe consider using pnpm or yarn instead or configure npm so that peer dependencies are not strict 💡

I like this npm error. It is genuinely obvious and I would like to avoid yarn or pnpm.

We just need to upgrade deps. LOL.

**Comment by dargmuesli** [comment]
Yeah, but no need to be pushy about it :smile:  v6 is compatible but just not marked as such yet. You can mark it as compatible yourself in package managers that support it. I'm sure people will get around to merge this PR when they have time to do so. If it takes some time, there might be more urgent tasks 🙊 also, if you really want that strictness and immediate updates at the same time, you always have the option to fork 🤙

**Comment by dargmuesli** [comment]
As this project is a community project, another idea is to join that community and become a maintainer :bulb:

**Comment by frederikhors** [comment]
> become a maintainer

how?

**Comment by dargmuesli** [comment]
> ## Introduction of the “community plugins”
> ...
> *All the above plugins will be eligible for repository ownership transfer based on relevant past contributions.*

https://github.com/dotansimha/graphql-code-generator/issues/9456

I'm sure dotansimha or saihaj will be able to assist with that.

**Comment by frederikhors** [comment]
@dargmuesli can you please merge this?

**Comment by dargmuesli** [comment]
I do not have merge permissions, I only created the PR

**Review by n1ru4l — APPROVED** [review]

**Pull request merged**
