### PR TITLE
feat : [typescript-react-apollo] support useSuspenseQuery

### PR DESCRIPTION
**Pull request by Hal-ang**
## Description

Implemented useSuspenseQuery, which was added in [apollo 3.8.0 version](https://www.apollographql.com/docs/react/data/suspense).

Related #388 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [x] This change requires a documentation update

## Screenshots/Sandbox (if appropriate/relevant):

Adding links to sandbox or providing screenshots can help us understand more about this PR and take
action on it as appropriate

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can
reproduce. Please also list any relevant details for your test configuration

- [x] I ran codegen with the changes applied to the project that is actually using the library, and confirmed that useSuspenseQuery was working properly. (with patch-package)
- [x] passed `yarn run test` after update snapshot file

**Test Environment**:

- OS: Mac OS
- `@graphql-codegen/typescript-react-apollo@3.3.7`:
- NodeJS: 18.17.1

## Checklist:

- [x] I have followed the
      [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the
      style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Hal-ang** [comment]
@saihaj 
Hi, Could you review this PR? thx :D

**Review by saihaj — APPROVED** [review]

**Comment by Hal-ang** [comment]
sorry. If I understand correctly, is it correct that the test failure of github action is resolved when the test code changes in my PR are merged? I'm not sure what part I need to fix separately. This is my first contribution, so please understand my lack of experience.

**Comment by saihaj** [comment]
hey @Hal-ang can you please run `yarn prettier . --write` and then commit that. That should make the prettier check happy
CleanShot 2023-09-11 at 16 58 04


for the failing tests you need to update all the snapshots I think 
CleanShot 2023-09-11 at 16 58 29

**Comment by Hal-ang** [comment]
Thanks! I pushed the new updated snapshot and prettier code

**Comment by Hal-ang** [comment]
HI, @saihaj :D
If you have a time, Could you please merge this PR? Thanks!

**Comment by saihaj** [comment]
actually I reverted things and CI on `main` should pass. You should try syncing this branch with `main` and then that should make CI happy 🤞🏼 @Hal-ang

**Comment by Hal-ang** [comment]
> actually I reverted things and CI on `main` should pass. You should try syncing this branch with `main` and then that should make CI happy 🤞🏼 @Hal-ang

Oh! Sorry for the late confirmation. thanks I tried to syncing a fork branch and checked test on my local :D
Screenshot 2023-10-01 at 12 04 27 PM

**Comment by saihaj** [comment]
hey @Hal-ang can you run `yarn generate:examples` and commit the changes?

CleanShot 2023-10-03 at 14 21 51

**Comment by Hal-ang** [comment]
It seems that the node-side settings of env in GitHub Actions do not work well. I'm not sure how to solve this, can you help me?
Screenshot 2023-10-09 at 1 16 12 PM

**Comment by fforres** [comment]
@saihaj @Hal-ang Really excited to see this feature :D 
Anything the rest of us can do to help? 
(Would love to use this as a base to add support to useBackgroundQuery 🙏, not sure what the state of the PR is)

**Review by saihaj — APPROVED** [review]
great work @Hal-ang!

**Comment by Grohden** [comment]
> New feature (non-breaking change which adds functionality)

isn't this a breaking change since it now **requires** apollo >= 3.8 and we can't opt out of suspense generation stuff?

**Pull request merged**
