### PR TITLE
breaking(graphcache): update graphcache plugin to support additional types in updates

### PR DESCRIPTION
**Pull request by JoviDeCroock**
## Description

This updates the graphCache plugin to adhere to changes we made in [5.2.0](https://github.com/urql-graphql/urql/blob/main/exchanges/graphcache/CHANGELOG.md#520)

- We now correctly support alternatively named root-type-names
- We now allow arbitrary type-field combination in our updaters

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)

## How Has This Been Tested?

The tests are updated to show the expected result.

## Checklist:

- [x] I have followed the
      [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the
      style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by saihaj** [comment]
looks like tests are failing @JoviDeCroock

**Comment by saihaj** [comment]
> @saihaj that is a Node 12 failure, or are you seeing others? Locally it all worked

this plugin shouldn't break node 12 though?

**Comment by JoviDeCroock** [comment]
Awesome, feel free to merge it whenever that's ready :)

**Review by saihaj — APPROVED** [review]

**Comment by ryanmt** [comment]
@saihaj cc @JoviDeCroock are there any blockers w/ moving this forward? This and #322 are preventing me from getting some bug fixes I'm looking forward to.

**Review by saihaj — APPROVED** [review]
thank you 🙏🏼

**Pull request merged**
