### PR TITLE
fix(preset/near-operation-file): read skipDocumentsValidation from config

### PR DESCRIPTION
**Pull request by HermanBilous**
## Description

Fixes build (I think)

Related #8222 #383 #214

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] This change requires a documentation update

## How Has This Been Tested?

Ran unit tests, but this change is mostly around types

## Checklist:

- [x] I have followed the
      [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the
      style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] ~~I have made corresponding changes to the documentation~~
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by HermanBilous** [comment]
Other than documentation, this should fix the issue. Not sure how to update the docs though.

**Comment by HermanBilous** [comment]
Also ran tests by `yarn build && yarn generate:examples`. I've tested it and the passed value is indeed used by cli. Only thing I had to do is upgrade the `@graphql-codegen/cli` package to v5.

**Comment by neil585456525** [comment]
Seems it's the pure type issue, they do have `skipDocumentsValidation` in the option root.
https://github.com/dotansimha/graphql-code-generator/blob/9df36440878a4af53d83b1989bb01e12a74642db/packages/utils/plugins-helpers/src/types.ts#L18

**Review by neil585456525 — APPROVED** [review]

**Comment by saihaj** [comment]
Hey @HermanBilous thanks for this. I revert a PR and then that particular one I opened it back up and looking for help to land #414 back. Do you want to help land those changes cause I assume resolving conflicts on this PR would mean we just close it out 🤔

**Comment by HermanBilous** [comment]
Hey @saihaj, I rebased the change onto your branch. Please review.

**Comment by saihaj** [comment]
let me merge and see if that PR turns green

**Pull request merged**
