### PR TITLE
fix(graphql-request): return errors in return type for rawRequest

### PR DESCRIPTION
**Pull request by dseeto**
## Description

Adds back the `errors?: GraphQLError[];` key/value to the response object when `rawRequest: true`.  This feature was added to `graphql-request` in this [change](https://github.com/jasonkuhrt/graphql-request/pull/352) as part of [supporting error policies](https://github.com/jasonkuhrt/graphql-request#errorpolicy).

For context, this was previously already added, but [was removed](https://github.com/dotansimha/graphql-code-generator/pull/7676) as the addition predated the implementation in `graphql-request` linked above.  

Related #183 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Update the snapshots used in `graphql-request-spec.ts` contain the expected `errors?` key

## Checklist:

- [x] I have followed the
      [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the
      style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] ~~I have made corresponding changes to the documentation~~ N/A
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] ~~Any dependent changes have been merged and published in downstream modules~~ N/A

### CODE REVIEW

**Comment by dseeto** [comment]
@saihaj @n1ru4l PTAL or please help tag the relevant maintainer. Builds are currently also failing due to https://github.com/dotansimha/graphql-code-generator-community/pull/383.

**Comment by saihaj** [comment]
> @saihaj @n1ru4l PTAL or please help tag the relevant maintainer. Builds are currently also failing due to https://github.com/dotansimha/graphql-code-generator-community/pull/383.

Yeah I wanted to fix this last week but haven't gotten around it. This week at GraphQL Conf. So hopefully can resolve it when I am home next week

**Comment by saihaj** [comment]
Hey @dseeto can you sync your PR with `main` and see if that resolves failing build issues?

**Comment by dseeto** [comment]
@saihaj merged. Looks like the Github Testing action says it needs approval from maintainer in order to run.

**Comment by dseeto** [comment]
Sorry for the back and forth, looks like `types.urql.tsx` was outdated. Ran `yarn generate:examples` to regenerate.

**Comment by saihaj** [comment]
@dseeto can you run `yarn generate:examples` and commit the changes. I think `dev-tests` need to be updated for this change

**Comment by saihaj** [comment]
thank you @dseeto

**Pull request merged**
