### PR TITLE
Fix/c sharp member name casing

### PR DESCRIPTION
**Pull request by mariusmuntean**
## Description

Using new config option named `memberNameConvention`, the casing of the interface/class/record members can be controlled.
Supported values are `camelCase` and `pascalCase`.
The default value is `camelCase` to avoid unexpected behaviour of this plugin from the people already using it.

Related #798 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

Added tests for interface, class and records where both `camelCase` and `pascalCase` naming is tested.

- [x] Should generate camelCase properties for input type fields
- [x] Should generate pascalCase properties for input type fields
- [x] Should generate a C# class with camel case property names for type
- [x] Should generate a C# class with pascal case property names for type
- [x] Should generate C# record with camel case property names
- [x] Should generate C# record with pascal case property names
- [x] Should generate C# interface with camelCase properties
- [x] Should generate C# interface with pascalCase properties

**Test Environment**:

- OS: macOS 14.5
-  "@graphql-codegen/c-sharp-common": "1.0.0",
-  "@graphql-codegen/plugin-helpers": "^3.0.0",
-  "@graphql-codegen/visitor-plugin-common": "^2.12.1",
-  "change-case-all": "1.0.15",
-  "tslib": "~2.6.0",
-  "unixify": "^1.0.0"
- NodeJS: v16.13.2

## Checklist:

- [x] I have followed the
      [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the
      style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by saihaj — COMMENTED** [review]
can you run `yarn changeset` and explain the changes there so it can be part of release notes. Other than that seems reasonable to me

**Comment by mariusmuntean** [comment]
@saihaj I added the changeset with the type minor because there's no braking change, just new functionality.

**Review by saihaj — APPROVED** [review]
great work!

**Comment by mariusmuntean** [comment]
Besides this plugin (`c-sharp`) there's the `c-sharp-operations` plugin. I think the `c-sharp-operations` plugin would benefit from the new config as well.
I'm volunteering again to make the new config available in `c-sharp-operations` as well.

Should I open a new issue or can I start working on the PR right away?

**Comment by saihaj** [comment]
> I'm volunteering again to make the new config available in c-sharp-operations as well.

Thank you! 

> can I start working on the PR right away?

feel free to just send in the PR

**Comment by mariusmuntean** [comment]
@saihaj  I added a new PR (#816) to add the same functionality to the `c-sharp-operations` plugin. I used this opportunity to move any shared code to c-sharp-common to avoid duplication.

**Comment by saihaj** [comment]
released [@graphql-codegen/c-sharp@5.1.0](https://github.com/dotansimha/graphql-code-generator-community/releases/tag/release-1725547706606)

**Pull request merged**
