### PR TITLE
feat(typescript-rtk-query): add importAlternateApiName to conifg options

### PR DESCRIPTION
**Pull request by DominicGBauer**
## Description
Allows a user to change the imported api name that comes from baseApi.ts. 

Example:
```
importBaseApiAlternateName: 'alternateApiName'
```
results in 
```
import  { alternateApiName } from './baseApi.ts'
```

Related [(issue)](https://github.com/dotansimha/graphql-code-generator-community/issues/68)

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
I've added an additional unit test following the previous tests' pattern.

### CODE REVIEW

**Review by saihaj — CHANGES_REQUESTED** [review]
We can ship this but can you add a changeset explaining your changes? (learn more https://github.com/dotansimha/graphql-code-generator-community/pull/75#issuecomment-1408078455)

**Comment by DominicGBauer** [comment]
@saihaj on it!

**Comment by DominicGBauer** [comment]
@saihaj I've added a changeset. Not sure if this is what is expected, if not could you please point me to an example :)?

**Review by saihaj — APPROVED** [review]

**Comment by saihaj** [comment]
Great work @DominicGBauer will wait for CI to be green and the merge it!

**Pull request merged**
