### PR TITLE
feat (msw) add withSuffix param

### PR DESCRIPTION
**Pull request by neil585456525**
## Description

Add a `withSuffix` param to allow user use typescript-msw [link](https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-msw#link) feature without forcing to use it with suffix

Related # (issue)

- [issue-384](https://github.com/dotansimha/graphql-code-generator-community/issues/384)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [x] This change requires a documentation update

## Screenshots/Sandbox (if appropriate/relevant):

Adding links to sandbox or providing screenshots can help us understand more about this PR and take
action on it as appropriate

## How Has This Been Tested?

Add `withSuffix:false` in the msw pludin link configuration.

## Checklist:

- [x] I have followed the
      [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the
      style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by saihaj — COMMENTED** [review]
can you create a changeset?

**Comment by neil585456525** [comment]
> can you create a changeset?

Added, thx for remiding

**Comment by saihaj** [comment]
> > can you create a changeset?
> 
> Added, thx for remiding

can you take a look why tests are failing ?


CleanShot 2023-09-12 at 22 38 16

**Comment by neil585456525** [comment]
#409

**Comment by saihaj** [comment]
hey @neil585456525 can you try rebasing this PR with `main`?

**Comment by neil585456525** [comment]
@saihaj Done

**Review by saihaj — APPROVED** [review]

**Pull request merged**
