### PR TITLE
fix(flutter-freezed): missing comma in enums

### PR DESCRIPTION
**Pull request by MitkoTschimev**
Add missing trailing comma for enum values

Before
```dart
enum AssetOrder {
  @JsonKey(name: 'contentType_ASC')
  contentTypeAsc
  @JsonKey(name: 'contentType_DESC')
  contentTypeDesc
}
```
Now
```dart
enum AssetOrder {
  @JsonKey(name: 'contentType_ASC')
  contentTypeAsc,
  @JsonKey(name: 'contentType_DESC')
  contentTypeDesc,
}
```

🚨 **IMPORTANT: Please do not create a Pull Request without creating an issue first.**

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Related # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots/Sandbox (if appropriate/relevant):

Adding links to sandbox or providing screenshots can help us understand more about this PR and take action on it as appropriate

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Environment**:

- OS:
- `@graphql-codegen/...`:
- NodeJS:

## Checklist:

- [ ] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by saihaj** [comment]
@Parables can you check this out?

**Review by saihaj — COMMENTED** [review]
we should add a test for this

**Comment by Parables** [comment]
@MitkoTschimev thanks for trying out this plugin and for the PR. I sincerely appreciate your contribution

To get your PR merged, please complete the following: 
- [ ] Run `yarn && yarn test -u` to Update the tests. This will update the `tests/plugin.spec.ts` from `line 42 - 144`

**Comment by Parables** [comment]
> we should add a test for this

@saihaj  how can I do that on my end here and push it back into this PR?

**Comment by saihaj** [comment]
> > we should add a test for this
> 
> 
> 
> @saihaj  how can I do that on my end here and push it back into this PR?

I think @MitkoTschimev can update tests?

**Comment by Parables** [comment]
> @MitkoTschimev thanks for trying out this plugin and for the PR. I sincerely appreciate your contribution
> 
> To get your PR merged, please complete the following:
> 
> * [ ]  Run `yarn && yarn test -u` to Update the tests. This will update the `tests/plugin.spec.ts` from `line 42 - 144`

@MitkoTschimev, please do this and let's get this fixed as soon as possible. 
I don't mean to pressure you but this is a critical issue. It renders this plugin and its output totally useless

**Comment by MitkoTschimev** [comment]
Let me take a look tomorrow to fix the tests

**Comment by Parables** [comment]
@MitkoTschimev, any updates on this?

If it's okay with you, I can fix this and tag you on the PR attributing the fix to you.

**Comment by Parables** [comment]
@saihaj please can we get this PR merged now

**Comment by Parables** [comment]
@MitkoTschimev I love your suggestion... I will get that done ASAP

**Comment by saihaj** [comment]
@MitkoTschimev can you add a changeset for this? run `yarn changeset` and then do a `patch` update for the plugin and explain your changes

**Comment by MitkoTschimev** [comment]
Give me a second ;) just coming back from a nursery event from my son :)

**Comment by MitkoTschimev** [comment]
I never worked with changeset but is this correct what happened?
Changeset created a folder and file. Should I commit this one?

image

**Comment by Parables** [comment]
@MitkoTschimev you can include the before and after code snippet you used in the issue to add a bit of context about the change

**Comment by saihaj** [comment]
https://github.com/dotansimha/graphql-code-generator-community/releases/tag/release-1675282344073

**Comment by Parables** [comment]
@saihaj please proceed to release this

I will submit another one that addresses some typos and misleading code samples in the guide and the plugin config as well as the live demo

**Pull request merged**
